hw2
NatashaFedorova/nodejs-homework-rest-api pull request #1
Opened 2023-03-09 17:33 UTC by NatashaFedorova

2023-03-09 22:15 UTC, KhYulian requested changes
Потрібні правки

2023-03-09 22:15 UTC, KhYulian commented on routes/api/contacts.js
> +  }
```suggestion
  } catch (error) {
    next(error);
  }
```

2023-03-09 22:15 UTC, KhYulian commented on routes/api/contacts.js
> +    });
схеми joi винесіть в окремий файл

2023-03-09 22:15 UTC, KhYulian commented on routes/api/contacts.js
> +    }
за валідацію відповідатиме joi, тому ці перевірки непотрібні

2023-03-09 22:15 UTC, KhYulian commented on routes/api/contacts.js
> +    const validationResult = schema.validate(req.body);
```suggestion
    const {error} = schema.validate(req.body);
```

2023-03-09 22:15 UTC, KhYulian commented on routes/api/contacts.js
> +    }
```suggestion
    if (error) {
      return res
        .status(400)
        .json({ status: validationResult.error.details[0].message });
    }
```

2023-03-09 22:15 UTC, KhYulian commented on routes/api/contacts.js
> +    }
за це також відповідає joi

2023-03-09 22:15 UTC, KhYulian commented on routes/api/contacts.js
> +    });
також винесіть

2023-03-09 22:16 UTC, KhYulian commented
окрема middleware, буде хорошим рішенням. Можете спробувати реалізувати в наступній дз

2023-03-10 09:34 UTC, NatashaFedorova commented
Добрий день. Я внесла зміни. Дякую, що допомогли доробити. Ви написали, що окремі middlewares реалізувати в наступній дз, а валідація не є middleware?

2023-03-10 16:39 UTC, KhYulian approved these changes
Чудова робота ❤️

2023-03-10 16:41 UTC, KhYulian commented
> Добрий день. Я внесла зміни. Дякую, що допомогли доробити. Ви написали, що окремі middlewares реалізувати в наступній дз, а валідація не є middleware?

const addPostValidation = (req, res, next) => { в даному випадку це middleware. Я мав на увазі, що можна створити більш універсальну функцію, яка прийматиме схему joi, та повертатиме middleware

2023-03-10 16:41 UTC, merged