hw03
NatashaFedorova/nodejs-homework-rest-api pull request #2
Opened 2023-03-18 18:44 UTC by NatashaFedorova

Добрий день. Внесла зміни до структури папок, якщо це не принципово, хотіла б залишити. Перевірка при POST на наявність документів з такики name, email, phone вийшла громіздка. Вирішила, що вона має бути, може правда лише на один кретерій.  Може щось порадите чи потрібна вона взагалі та як краще оформити?

2023-03-18 18:47 UTC, NatashaFedorova commented
> Добрий день. Внесла зміни до структури папок, якщо це не принципово, хотіла б залишити. Перевірка при POST на наявність документів з такики name, email, phone вийшла громіздка. Вирішила, що вона має бути, може правда лише на один кретерій. Може щось порадите чи потрібна вона взагалі та як краще оформити?
Можна змінити формат запису phone?
Дякую

2023-03-19 10:10 UTC, KhYulian requested changes
Потрібне доопрацювання

2023-03-19 10:10 UTC, KhYulian commented on models/useModel.js
useModel.js => Contact.js

2023-03-19 10:10 UTC, KhYulian commented on validation/index.js
Валідація справді дуже громіздка. Можна значно спростити. 
```javascript
const validateBody = (schema) => {
  return (req, res, next) => {
    const { error } = schema.validate(req.body);

    if (error) {
      return next(error);
    }

    next();
  };
};

module.exports = { validateBody };
```

2023-03-19 10:10 UTC, KhYulian commented on routes/contactsRoutes.js
> +router.route('/').post(checkContactData, addContact).get(getContacts);
```suggestion
router.route('/').post(validateBody(JoiSchemaForCreatingContact) , addContact).get(getContacts);
```

2023-03-19 10:10 UTC, KhYulian commented on validation/joiValidation.js
> +
непотрібно створювати такі функції. Достатно написати схему.
```javascript
const postContactValidationSchema = Joi.object()
    .keys({
      name: Joi.string().min(3).max(30).required().trim(),
      email: Joi.string()
        .email({
          minDomainSegments: 2,
          tlds: { allow: ['com', 'net', 'uk', 'org', 'ca'] },
        })
        .required()
        .trim(),
      phone: Joi.string().required().trim(),
      favorite: Joi.boolean(),
    })
```

2023-03-19 14:10 UTC, NatashaFedorova commented
Добрий день. Зміни внесла)) Додала get "contacts/favorite" - лише улюблені. Дякую за рекомендації

2023-03-19 16:42 UTC, KhYulian approved these changes
Чудова робота!

2023-03-21 11:43 UTC, merged